# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '# Use an existing image as the base image FROM node:18.14.0-alpine  # Set the working directory WORKDIR /app  # Copy the package.json and package-lock.json files to the container COPY package*.json ./  # Install the dependencies RUN npm install  # Copy the rest of the application files to the container COPY . .  # Set the environment variables (if any) ENV NODE_ENV production  # Expose the port on which your application is running EXPOSE 8080  # Command to run when the container starts CMD [ &quot;npm&quot;, &quot;start&quot; ]'
        tags: |
          $(tag)
